basesURL = "https://www.pliclock.com"
languageCode = "en-us"
title = "PlicLock"
author = "YP_hack"
copyright = "Powered by Hugo. @2021 YP_hack"
theme = "hugo-uno"
hasCJKLanguage = "true"

[Params]
description = "Design by PlicLock"
github = "ysk0518"
logo = "/images/plic_lock.png"

[taxonomies]
tag = "tags"
archive = "archives"

[permalinks]
